### ISSUE TITLE
Merge mouse whole cell + infiltrating immune cell in cancer

### ISSUE THREAD

**Issue by mHagiw** [KevinMenden/scaden#114]
Hi Kevin.

I want to know the percentage of a subset of immune cells in tumor cells in mouse.

So, I'm thinking of combining scRNA-seq data of mouse whole body cells and immune cells isolated from tumors in mouse cancer transplantation models to make simulate data and make predictions.

Do you think this method is possible from a producer's point of view?

This simulate data have about 100 cell types.

May I have your suggestion on this issue? Thanks a lot!

Masaki

**Comment by KevinMenden** [comment]
Hi Masaki,

it certainly sounds feasible. But I cannot tell how you good this will work in the end, as I haven't tested this with Scaden (or any other deconvolution method). 

Generally all I can tell you (unfortunately) is that the training dataset/tissue should be as close as possible to the target dataset. With every little bit you go away from that, you will loose some precision. And unfortunately, currently Scaden isn't able to tell. I wanted to add uncertainty measurements to Scaden for a long time now but didn't find the time so far - maybe this winter I can add it. This would then allow you to do these kind of experiments and hopefully Scaden could tell you how much you can trust the results.

So if it's not too much work for now I would say try it out, maybe also user another deconvolution algorithm on top. If both methods agree to some extent, you can probably trust your results.

Good luck!
Kevin

**Comment by mHagiw** [comment]
Thank you for your reply.

As you said, we will try to match the cell subset of dataset with the bulk data.

Also, another question for the same test, 
would it be more accurate to define the cell types without being too specific?

For example, I have been dividing CD8 T cells into Tcm, Trm, Tex and so on, but I have the impression that I cannot divide them accurately.

Masaki

**Comment by solitudetuzi** [comment]
Hello, kevin.

 I'm very sorry to bother you this year. I am a graduate student and a beginner in the field of single cell. Your scaden's thesis is the first one I have studied. I want to learn about bioinformatics from this yours.
I am studying scaden, I have done the first experiment in your thesis.
Use pbmc data (data6k, data8k, donorA, donorC) to be verified with scaden.
First, I used the pbmc.h5ad data you provided for model training,
Use the data6k_500_samples.txt ， data8k_500_samples.txt， donorA_500_samples.txt   donorC_500_samples.txt provided by you as the prediction file, and compare the prediction results with other methods.

Use scaden to predict the above data6k, data8k, donorA, donorC.samples, and compare with other methods to get good results.

I want to try other experiments in your article, such as pbmc1 and pmbc2 data, pancreas, mouse Brain, etc.
You provide downloads of these training data on the website, and use the following data for model training.

But in addition to the first pbmc experiment, the rest of the data set experiments, I found only the  **prediction.txt** and **labels .tx**t class files in the data you provided, after model training, can not predict and verify your conclusions.

I would like to ask you to provide me with a prediction document on this data, namely the sample .txt documents, so that  can better study your paper.
This year, due to the lack of data, I can no longer go into further study.
I'm really, really sorry to have been interrupting you. I'd love to learn how your cell anti-convolution is done.
Thank you so much.

**Comment by KevinMenden** [comment]
Hi Masaki,

sorry for the late reply, I was busy and then on holiday.

Yes definitely, dividing T cells too much will result in poor performance. At some point the difference between the cell types gets lost in all the noise.

Best,
Kevin

**Comment by mHagiw** [comment]
Hi Kevin.

Thank you very much for kind reply.

I will try according to you say !!

Best,
Masaki
