### ISSUE TITLE
tensorflow vs tensorflow-gpu

### ISSUE THREAD

**Issue by zeehio** [KevinMenden/scaden#30]
When using pip to install scaden, scaden always pulls `tensorflow` and never `tensorflow-gpu`.

The real problem is that *pip* is not able to deal with GPU variants, as described at https://github.com/tensorflow/tensorflow/issues/7166. If pip was able, then tensorflow would not need to have those two separate packages and everything would work as expected.

There are three possible scenarios:

- BAD: We depend on `tensorflow`, and it is not possible to install scaden using the `tensorflow-gpu` package because they conflict. (this is the current status)
- UGLY: We publish to pypi two packages `scaden` and `scaden-gpu`, depending on tensorflow and tensorflow-gpu respectively.
- ALSO UGLY: We **optionally** depend on `tensorflow` and `tensorflow-gpu`. The instructions to install scaden through pip would be: `pip install scaden[cpu]` or `pip install scaden[gpu]`. `pip install scaden` would not install any tensorflow variant and lead to an error (we could warn the user then, though).

I can easily implement `ALSO UGLY`, the community is split between the two ugly solutions. Do you have any preference, @KevinMenden ?

**Comment by KevinMenden** [comment]
I have thought about this in the past, and my preferred solution would have been to generate a scaden-gpu package - mostly because the majority of users (I believe) won't have a GPU and would just want to do `pip install scaden`

However now that I think of it , ALSO UGLY might be a better solution for now. I don't really like the idea of having two different packages for the same software .... so I guess we go with this for now?

**Comment by zeehio** [comment]
Another option is leave only the CPU version on pip, as it is now, and provide docker images and instructions for cpu & gpu

**Comment by KevinMenden** [comment]
That might actually be the best version for now.
For GPU, you can basically just install Scaden via pip, then uninstall tensorflow and install tensorflow-gpu. And we can easiily provide a container that has this.
