### ISSUE TITLE
Problem creating h5ad-file

### ISSUE THREAD

**Issue by idalarsson** [KevinMenden/scaden#38]
Hello again,

I've now managed to get bulk_generation.py to work on my data, but encounter an error when trying to create the h5ad-file. The error message is:

```
Celltypes: [1, 2, 3, 4, 5, 6]
Traceback (most recent call last):
  File "create_h5ad_file.py", line 98, in <module>
    y = sort_celltypes(y, labels, celltypes)
  File "create_h5ad_file.py", line 55, in sort_celltypes
    idx = [labels.index(x) for x in ref_labels]
  File "create_h5ad_file.py", line 55, in <listcomp>
    idx = [labels.index(x) for x in ref_labels]
ValueError: 1 is not in list
```

Does this tell you anything?

**Comment by KevinMenden** [comment]
Hi Ida,

it looks like some mismatch between the labels and the ref_labels. That could be caused by a difference in cell type names between your cell type file and the files created by bulk_generation.py. But it is really hard to say with that information.

If you can send me some part of your files, I could help you. Otherwise I would double-check that the cell type names are matching.

Let me know if that helps!

Kevin

**Comment by idalarsson** [comment]
Ok! 

My cell type labels are 1,2,3,4,5,6 which seems to be read properly according to the first code line which I pasted in the message above.

The 'celltypes.txt'-file created by bulk_generation.py looks like this:
[celltypes.txt](https://github.com/KevinMenden/scaden/files/5369979/celltypes.txt)

There are some zeroes in this file, but I'm not very familiar with python so I don't know if they are there for file reading purposes? Otherwise that could be the problem I guess.

//Ida

**Comment by idalarsson** [comment]
And here are the labels file generated by bulk_generation.py:
[barcoding_labels.txt](https://github.com/KevinMenden/scaden/files/5370022/barcoding_labels.txt)

**Comment by KevinMenden** [comment]
Great, thanks! So that looks pretty normal :-)

I suspect that the variable types don't match (string and int), because the labels are just numbers.
To test this I've modified the script a bit, could you quickly test this?

(Had to Zip it because you can't upload python files here)

[create_h5ad_mod.py.zip](https://github.com/KevinMenden/scaden/files/5370051/create_h5ad_mod.py.zip)

**Comment by idalarsson** [comment]
Hmm ok this seems to have solved the first problem but now it threw a new error... ;)

```
Celltypes: ['1', '2', '3', '4', '5', '6']
Processing barcoding
Traceback (most recent call last):
  File "create_h5ad_mod.py", line 109, in <module>
    adata.append(anndata.AnnData(X=x.as_matrix(),
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 5139, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'as_matrix'


```

**Comment by KevinMenden** [comment]
Oops, my bad, try this one:

[create_h5ad_mod.py.zip](https://github.com/KevinMenden/scaden/files/5370145/create_h5ad_mod.py.zip)

**Comment by idalarsson** [comment]
Yes this worked!! Thanks!

It did create a warning but no error, but will paste it here just so you know:

```
Celltypes: ['1', '2', '3', '4', '5', '6']
Processing barcoding
/usr/local/lib/python3.8/site-packages/anndata/_core/anndata.py:119: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/usr/local/lib/python3.8/site-packages/anndata/_core/anndata.py:1192: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  if is_string_dtype(df[key]) and not is_categorical(df[key])
... storing 'ds' as categorical
```

Thank you so much, great support!

**Comment by KevinMenden** [comment]
Cool, glad I could help :-) 

And thanks for the warning!

Cheers,
Kevin
