### ISSUE TITLE
Normalization of the training expression data

### ISSUE THREAD

**Issue by HelloYiHan** [KevinMenden/scaden#73]
Hi Kevin Menden,

Thank you for your excellent work. 

I was wondering what kind of normalization were the numbers (numbers in the .X data matrix of the .h5ad file) in the PBMC training expression dataset (https://scaden.readthedocs.io/en/latest/datasets/) applied? TPM, RPKM, or log-transformed counts?

Thank you for your time.

Yi Han

**Comment by KevinMenden** [comment]
Hi Yi Han,

the training datasets for PBMC are from 10X Genomics scRNA-seq datasets. They have been normalized per cell, so basically library-size normalization.

Before training, you will have to use the `scaden process` command, which performs some further normalization, including log-transformation.

Hope that helps!

Best,
Kevin

**Comment by HelloYiHan** [comment]
Hi Kevin,

The scRNA-Seq datasets were library-size normalized, but I was thinking the simulated PBMC training dataset (pbmc_data.h5ad) might not be library-size normalized. Because when I typed the codes:
```python
import numpy as np
print(np.mean(pbmch5ad.X,axis=1))
```
the results were:
[138.89468 139.15628 139.081   ...  65.73269  65.76049  66.02885]

I was wondering if the simulated PBMC training dataset could be seen as raw count data.

Thank you for your kind help.

Best,
Yi

**Comment by KevinMenden** [comment]
Hi Yi,

that's correct, the scRNA-seq data is normalized per library size, while no immediate additional normalisation is applied to the simulated data. This is then handled by the `process` method, which required the target bulk data as well. 

I would not go as far to call it raw count data though, because it has been normalised at the cell level, and doesn't consist of actual counts anymore. 

Hope that answers your question - if not, let me know!

Best,
Kevin
